In [1]:
import json
import argparse
import functools
import itertools

In [6]:
import torch
import numpy as np 
from torch import nn
import torch.nn.functional as F

In [9]:
input = torch.tensor(
    [[0.1, 0.9],
    [0.3, 0.7],
    [0.7, 0.3]]
).float()

target = torch.tensor(
    [[0, 1],
     [1, 0],
     [1, 0]]
).float()

input, target

(tensor([[0.1000, 0.9000],
         [0.3000, 0.7000],
         [0.7000, 0.3000]]),
 tensor([[0., 1.],
         [1., 0.],
         [1., 0.]]))

In [24]:
weight = torch.sum(target, dim=0) / len(target)
loss = F.cross_entropy(input=input, target=target, weight=weight, reduction="none")

actual = torch.argmax(target, dim=-1)
p_t = input[range(len(input)), actual]
focal_loss = loss * ((1 - p_t) ** 2)

print(p_t)
print(loss)
print(focal_loss)

tensor([0.9000, 0.3000, 0.7000])
tensor([0.1237, 0.6087, 0.3420])
tensor([0.0012, 0.2983, 0.0308])
